package com.tacticlogistics.application.tasks.etl.components.tactic.oms.ordenes;

public enum MacroExcelOrdenDtoAtributos {
    ID_CARGA    ("ID_CARGA"),
    TIPO_SERVICIO_CODIGO_ALTERNO ("TIPO_SERVICIO_CODIGO_ALTERNO"),
    
    CLIENTE_CODIGO ("CLIENTE"),
    NUMERO_ORDEN_COMPRA ("NUMERO_ORDEN_COMPRA"),
    NUMERO_ORDEN ("NUMERO_ORDEN"),
    FECHA_ORDEN ("FECHA_ORDEN"),
    CLIENTE_RECOGE ("CLIENTE_RECOGE"),

    DESTINATARIO_CANAL_CODIGO ("DESTINATARIO_CANAL"),
    DESTINATARIO_IDENTIFICACION ("DESTINATARIO_IDENTIFICACION"),
    DESTINATARIO_NOMBRE ("DESTINATARIO_NOMBRE"),

    DESTINO_CIUDAD_NOMBRE_ALTERNO   ("DESTINO_CIUDAD"),
    DESTINO_DIRECCION ("DESTINO_DIRECCION"),
    DESTINO_NOMBRE ("DESTINO_NOMBRE"),
    DESTINO_CONTACTO_EMAIL ("DESTINO_EMAIL"),
    DESTINO_CONTACTO_NOMBRES ("DESTINO_CONTACTO"),
    DESTINO_CONTACTO_TELEFONOS ("DESTINO_TELEFONOS"),
    
    ORIGEN_CIUDAD_NOMBRE_ALTERNO   ("ORIGEN_CIUDAD"),
    ORIGEN_DIRECCION   ("ORIGEN_DIRECCION"),
    ORIGEN_NOMBRE ("ORIGEN_NOMBRE"),
    ORIGEN_CONTACTO_EMAIL ("ORIGEN_EMAIL"),
    ORIGEN_CONTACTO_NOMBRES ("ORIGEN_CONTACTO"),
    ORIGEN_CONTACTO_TELEFONOS ("ORIGEN_TELEFONOS"),
    
    CONFIRMAR_CITA ("CONFIRMAR_CITA"),
    FECHA_MINIMA   ("FECHA_MINIMA"),
    FECHA_MAXIMA   ("FECHA_MAXIMA"),
    HORA_MINIMA ("HORA_MINIMA"),
    HORA_MAXIMA ("HORA_MAXIMA"),
    VALOR_RECAUDO  ("VALOR_RECAUDO"),
    NOTAS ("NOTAS"),

    LINEA_DESCRIPCION   ("LINEA_DESCRIPCION"),
    LINEA_PRODUCTO_CODIGO   ("LINEA_PRODUCTO"),
    LINEA_CANTIDAD_SOLICITADA   ("LINEA_CANTIDAD"),

    LINEA_BODEGA_ORIGEN_CODIGO  ("LINEA_BODEGA_ORIGEN"),
    LINEA_ESTADO_ORIGEN ("LINEA_ESTADO_ORIGEN"),
    LINEA_BODEGA_DESTINO_CODIGO ("LINEA_BODEGA_DESTINO"),
    LINEA_ESTADO_DESTINO ("LINEA_ESTADO_DESTINO"),

    LINEA_VALOR_DECLARADO_POR_UNIDAD    ("LINEA_VALOR_DECLARADO_POR_UNIDAD"),
    LINEA_PREDISTRIBUCION_DESTINO_FINAL ("LINEA_PREDISTRIBUCION_DESTINO_FINAL"),
    LINEA_PREDISTRIBUCION_ROTULO ("LINEA_PREDISTRIBUCION_ROTULO"),

    LINEA_LOTE  ("LINEA_LOTE"),
    LINEA_SERIAL ("LINEA_SERIAL"),
    LINEA_COSECHA ("LINEA_COSECHA"),
    LINEA_BL ("LINEA_BL"),
    LINEA_FONDOCUENTA ("LINEA_FONDOCUENTA"),
    LINEA_DISTRIBUIDO ("LINEA_DISTRIBUIDO"),
    LINEA_ESTAMPILLADO ("LINEA_ESTAMPILLADO"),
    LINEA_IMPORTE ("LINEA_IMPORTE"),
    LINEA_NUTRICIONAL ("LINEA_NUTRICIONAL"),
    LINEA_ORIGEN ("LINEA_ORIGEN"),
    LINEA_SALUD ("LINEA_SALUD"),
    LINEA_PINADO ("LINEA_PINADO")
    ;

    private final String text;

    private MacroExcelOrdenDtoAtributos(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return text;
    }
}
