package com.tacticlogistics.application.task.etl;

public enum MacroExcelOrdenDtoAtributos {
    ID_CARGA    ("ID_CARGA"),
    TIPO_SERVICIO_CODIGO_ALTERNO ("TIPO_SERVICIO_CODIGO_ALTERNO"),
    
    CLIENTE_CODIGO ("CLIENTE"),
    NUMERO_CONSOLIDADO ("NUMERO_CONSOLIDADO"),
    NUMERO_ORDEN ("NUMERO_ORDEN"),

    DESTINO_CIUDAD_NOMBRE_ALTERNO   ("DESTINO_CIUDAD"),
    DESTINO_DIRECCION ("DESTINO_DIRECCION"),

    ORIGEN_CIUDAD_NOMBRE_ALTERNO   ("ORIGEN_CIUDAD"),
    ORIGEN_DIRECCION   ("ORIGEN_DIRECCION"),

    CLIENTE_RECOGE ("CLIENTE_RECOGE"),
    CONFIRMAR_CITA ("CONFIRMAR_CITA"),
    
    FECHA_ENTREGA_MINIMA   ("FECHA_ENTREGA_MINIMA"),
    FECHA_ENTREGA_MAXIMA   ("FECHA_ENTREGA_MAXIMA"),
    HORA_ENTREGA_MINIMA ("HORA_ENTREGA_MINIMA"),
    HORA_ENTREGA_MAXIMA ("HORA_ENTREGA_MAXIMA"),

    DESTINATARIO_CANAL_CODIGO_ALTERNO ("DESTINATARIO_CANAL"),
    DESTINATARIO_IDENTIFICACION ("DESTINATARIO_IDENTIFICACION"),
    DESTINATARIO_NOMBRE ("DESTINATARIO_NOMBRE"),

    DESTINO_NOMBRE ("DESTINO_NOMBRE"),
    DESTINO_CONTACTO_EMAIL ("DESTINO_EMAIL"),
    DESTINO_CONTACTO_NOMBRES ("DESTINO_CONTACTO"),
    DESTINO_CONTACTO_TELEFONOS ("DESTINO_TELEFONOS"),
    
    ORIGEN_NOMBRE ("ORIGEN_NOMBRE"),
    ORIGEN_CONTACTO_EMAIL ("ORIGEN_EMAIL"),
    ORIGEN_CONTACTO_NOMBRES ("ORIGEN_CONTACTO"),
    ORIGEN_CONTACTO_TELEFONOS ("ORIGEN_TELEFONOS"),

    VALOR_RECAUDO  ("VALOR_RECAUDO"),
    NOTAS ("NOTAS"),

    LINEA_PRODUCTO_DESCRIPCION   ("LINEA_PRODUCTO_DESCRIPCION"),
    LINEA_PRODUCTO_CODIGO   ("LINEA_PRODUCTO"),
    LINEA_CANTIDAD_SOLICITADA   ("LINEA_CANTIDAD"),

    LINEA_BODEGA_ORIGEN_CODIGO  ("LINEA_BODEGA_ORIGEN"),
    LINEA_ESTADO_ORIGEN ("LINEA_ESTADO_ORIGEN"),

    LINEA_BODEGA_DESTINO_CODIGO ("LINEA_BODEGA_DESTINO"),
    LINEA_ESTADO_DESTINO ("LINEA_ESTADO_DESTINO"),
    
    LINEA_LOTE  ("LINEA_LOTE"),
    LINEA_SERIAL ("LINEA_SERIAL"),
    LINEA_COSECHA ("LINEA_COSECHA"),
    LINEA_ESTAMPILLADO ("LINEA_ESTAMPILLADO"),
    LINEA_SALUD ("LINEA_SALUD"),
    LINEA_IMPORTE ("LINEA_IMPORTE"),
    LINEA_DISTRIBUIDO ("LINEA_DISTRIBUIDO"),
    LINEA_NUTRICIONAL ("LINEA_NUTRICIONAL"),
    LINEA_ORIGEN ("LINEA_ORIGEN"),
    LINEA_BL ("LINEA_BL"),
    LINEA_FONDOCUENTA ("LINEA_FONDOCUENTA"),

    LINEA_PREDISTRIBUCION_DESTINO_FINAL ("LINEA_PREDISTRIBUCION_DESTINO_FINAL"),
    LINEA_PREDISTRIBUCION_ROTULO ("LINEA_PREDISTRIBUCION_ROTULO"),
    LINEA_VALOR_DECLARADO_POR_UNIDAD    ("LINEA_VALOR_DECLARADO_POR_UNIDAD")
    ;

    
    private final String text;

    private MacroExcelOrdenDtoAtributos(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return text;
    }
}
