package com.tacticlogistics.application.task.etl;

public enum OrdenDtoAtributos {
    ID_CARGA    ("ID_CARGA"),
    
    TIPO_SERVICIO_CODIGO_ALTERNO    ("TIPO_SERVICIO_CODIGO_ALTERNO"),
    
    CLIENTE_CODIGO  ("CLIENTE_CODIGO"),
    
    NUMERO_ORDEN  ("NUMERO_DOCUMENTO_ORDEN_CLIENTE"),
    PREFIJO_NUMERO_ORDEN("PREFIJO_NUMERO_DOCUMENTO_ORDEN_CLIENTE"),
    NUMERO_CONSOLIDADO    ("NUMERO_DOCUMENTO_CONSOLIDADO_CLIENTE"),
        
    CANAL_CODIGO_ALTERNO ("SEGMENTO_CODIGO_ALTERNO"),
        
    DESTINATARIO_NUMERO_IDENTIFICACION  ("DESTINATARIO_NUMERO_IDENTIFICACION"),
    DESTINATARIO_DIGITO_VERIFICACION    ("DESTINATARIO_DIGITO_VERIFICACION"),
    DESTINATARIO_CODIGO ("DESTINATARIO_CODIGO"),
    DESTINATARIO_NOMBRE ("DESTINATARIO_NOMBRE"),

    DESTINATARIO_CIUDAD_CODIGO_ALTERNO   ("DESTINATARIO_CIUDAD_CODIGO_ALTERNO"),
    DESTINATARIO_CIUDAD_NOMBRE_ALTERNO   ("DESTINATARIO_CIUDAD_NOMBRE_ALTERNO"),
    DESTINATARIO_DIRECCION   ("DESTINO_DIRECCION"),
    DESTINATARIO_DIRECCION_INDICACIONES  ("DESTINO_DIRECCION_INDICACIONES"),
    DESTINATARIO_CONTACTO_NOMBRES   ("DESTINATARIO_CONTACTO_NOMBRES"),
    DESTINATARIO_CONTACTO_EMAIL ("DESTINATARIO_CONTACTO_EMAIL"),
    DESTINATARIO_CONTACTO_TELEFONOS ("DESTINATARIO_CONTACTO_TELEFONOS"),
    
    DESTINATARIO_RECOGE ("DESTINATARIO_RECOGE"),
        
    DESTINO_CODIGO ("DESTINO_CODIGO"),
    DESTINO_NOMBRE ("DESTINO_NOMBRE"),

    BODEGA_DESTINO_CODIGO ("BODEGA_DESTINO_CODIGO"),
    BODEGA_DESTINO_NOMBRE ("BODEGA_DESTINO_NOMBRE"),
    
    DESTINO_CIUDAD_CODIGO ("DESTINO_CIUDAD_CODIGO"),
    DESTINO_CIUDAD_CODIGO_ALTERNO   ("DESTINO_CIUDAD_CODIGO_ALTERNO"),
    DESTINO_CIUDAD_NOMBRE_ALTERNO   ("DESTINO_CIUDAD_NOMBRE_ALTERNO"),
    DESTINO_DIRECCION   ("DESTINO_DIRECCION"),
    DESTINO_DIRECCION_INDICACIONES  ("DESTINO_DIRECCION_INDICACIONES"),
    DESTINO_CONTACTO_NOMBRES    ("DESTINO_CONTACTO_NOMBRES"),
    DESTINO_CONTACTO_EMAIL  ("DESTINO_CONTACTO_EMAIL"),
    DESTINO_CONTACTO_TELEFONOS  ("DESTINO_CONTACTO_TELEFONOS"),
        
    FECHA_SUGERIDA_ENTREGA_MINIMA   ("FECHA_SUGERIDA_ENTREGA_MINIMA"),
    FECHA_SUGERIDA_ENTREGA_MAXIMA   ("FECHA_SUGERIDA_ENTREGA_MAXIMA"),
    HORA_SUGERIDA_ENTREGA_MINIMA ("HORA_SUGERIDA_ENTREGA_MINIMA"),
    HORA_SUGERIDA_ENTREGA_MAXIMA ("HORA_SUGERIDA_ENTREGA_MAXIMA"),
    HORA_SUGERIDA_ENTREGA_MINIMA_ADICIONAL   ("HORA_SUGERIDA_ENTREGA_MINIMA_ADICIONAL"),
    HORA_SUGERIDA_ENTREGA_MAXIMA_ADICIONAL   ("HORA_SUGERIDA_ENTREGA_MAXIMA_ADICIONAL"),
    AJUSTAR_FECHA_ENTREGA_PROXIMO_DIA_HABIL("AJUSTAR_FECHA_ENTREGA_PROXIMO_DIA_HABIL"),
    AJUSTAR_FECHA_ENTREGA_PROXIMO_DIA_HABIL_PERMITIR_ENTREGAR_SABADOS("AJUSTAR_FECHA_ENTREGA_PROXIMO_DIA_HABIL_PERMITIR_ENTREGAR_SABADOS"),
    
    NOTAS_APROBACION_CLIENTE ("NOTAS_APROBACION_CLIENTE"),
    USUARIO_APROBACION_CLIENTE ("USUARIO_APROBACION_CLIENTE"),
    FECHA_APROBACION_CLIENTE ("FECHA_APROBACION_CLIENTE"),

    REQUERIMIENTOS_DISTRIBUCION ("REQUERIMIENTOS_DISTRIBUCION"),
    REQUERIMIENTOS_MAQUILA ("REQUERIMIENTOS_MAQUILA"),

    VALOR_RECAUDO   ("VALOR_TOTAL_RECAUDO"),
    REQUIERE_RECAUDO   ("REQUIERE_RECAUDO"),
    
    LINEAS  ("LINEAS"),
    LINEA_NUMERO_ITEM   ("LINEA_NUMERO_ITEM"),
    LINEA_PRODUCTO_DESCRIPCION   ("LINEA_PRODUCTO_DESCRIPCION"),
    LINEA_CANTIDAD_SOLICITADA   ("LINEA_CANTIDAD_SOLICITADA"),
    LINEA_CANTIDAD_PLANIFICADA   ("LINEA_CANTIDAD_PLANIFICADA"),
    LINEA_DESCRIPCION   ("LINEA_DESCRIPCION"),
    LINEA_VALOR_VENTA_POR_UNIDAD    ("LINEA_VALOR_VENTA_POR_UNIDAD"),
    LINEA_VALOR_DECLARADO_POR_UNIDAD    ("LINEA_VALOR_DECLARADO_POR_UNIDAD"),
        
    LINEA_PRODUCTO_CODIGO   ("LINEA_PRODUCTO_CODIGO"),
    LINEA_PRODUCTO_CODIGO_ALTERNO   ("LINEA_PRODUCTO_CODIGO_ALTERNO"),
    
    LINEA_UNIDAD_CODIGO ("LINEA_UNIDAD_CODIGO"),
    LINEA_UNIDAD_CODIGO_ALTERNO ("LINEA_UNIDAD_CODIGO_ALTERNO"),
    
    LINEA_TIPO_CONTENIDO_CODIGO ("LINEA_TIPO_CONTENIDO_CODIGO"),
    LINEA_TIPO_CONTENIDO_CODIGO_ALTERNO ("LINEA_TIPO_CONTENIDO_CODIGO_ALTERNO"),

    LINEA_BODEGA_ORIGEN_CODIGO  ("LINEA_BODEGA_ORIGEN_CODIGO"),
    LINEA_BODEGA_ORIGEN_CODIGO_ALTERNO  ("LINEA_BODEGA_ORIGEN_CODIGO_ALTERNO"),
    LINEA_BODEGA_DESTINO_CODIGO ("LINEA_BODEGA_DESTINO_CODIGO"),
    LINEA_BODEGA_DESTINO_CODIGO_ALTERNO ("LINEA_BODEGA_DESTINO_CODIGO_ALTERNO"),
        
    LINEA_LOTE  ("LINEA_LOTE"),
    LINEA_SERIAL ("LINEA_SERIAL"),
    LINEA_ESTADO ("LINEA_ESTADO"),
    LINEA_ESTAMPILLADO ("LINEA_ESTAMPILLADO"),
    LINEA_BL ("LINEA_BL"),
    LINEA_FONDOCUENTA ("LINEA_FONDOCUENTA"),
    LINEA_NOTAS ("LINEA_NOTAS"),

    LINEA_PREDISTRIBUCION_DESTINO_FINAL ("LINEA_PREDISTRIBUCION_DESTINO_FINAL"),
    LINEA_PREDISTRIBUCION_ROTULO ("LINEA_PREDISTRIBUCION_ROTULO"),

    LINEA_ORIGEN_CODIGO  ("LINEA_ORIGEN_CODIGO"),
    LINEA_ORIGEN_NOMBRE  ("LINEA_ORIGEN_NOMBRE");

    
    private final String text;

    private OrdenDtoAtributos(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return text;
    }
}
